version: '2'

services:

  elasticsearch:
    image: josemottalopes/iothasselk_elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    #restart: always
    networks:
      - elk

# TODO: check issue reported by log:
# logstash_1       | WARNING: An illegal reflective access operation has occurred
# logstash_1       | WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/usr/share/logstash/logstash-core/lib/jars/jruby-complete-9.2.7.0.jar) to field java.io.FileDescriptor.fd
# logstash_1       | WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
# logstash_1       | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
# logstash_1       | WARNING: All illegal access operations will be denied in a future release

  # logstash:
  #   image: josemottalopes/iothasselk_logstash
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     #ELASTIC_PASSWORD: changeme
  #   restart: always
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    image: josemottalopes/iothasselk_kibana
    build:
      context: kibana/
    #  args:
    #    ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    #restart: always
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
    